import {Fragment} from 'react'
// Components
import Head from 'next/head';
import Customers from './customers'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar';
//Pages
import HomePage from "./homePage";
import Services from './services';

export default function Home() {
    return (
        <Fragment>
        <Head className="font-semibold italic">
        <title>!NEWS </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Brackets.png" />
        </Head>
        <Navbar/>
        <HomePage/>
        <Services/>
        <Customers/>
        <Footer/>
        </Fragment>
    )

   }
