import {Fragment} from 'react'
// Components
import Head from 'next/head';
import Spa from './singlePageApp'
import Customers from './customers'
import Footer from '../components/Footer'

export default function Home() {
    return (
        <Fragment>
        <Head>
        <title>!NEWS </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Brackets.png" />
        </Head>
        <Spa/>
        <Customers/>
        <Footer/>
<p>Test</p>
        </Fragment>
    )

   }
