import {Fragment} from 'react'
// Components
import Head from 'next/head';
import Spa from './singlePageApp'

export default function Home() {
    return (
        <Fragment>
        <Head>
        <title>!NEXT </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Brackets.png" />
        </Head>
        <Spa/>
        </Fragment>
    )

   }
