//Pages
import HomePage from "./homePage";
import Services from './services';
import Customers from './customers'
import Projects from './projects';
import News from './news'
// Components
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer'

export default function Spa() {
  return (
      <div className="font-semibold italic">
    <Head>
      <title>!NEXT </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/Brackets.png" />
    </Head>
    <Navbar/>
    <HomePage/>
    <br/>
    <Services/>
    <Projects/>
    <News/>
    <Customers/>
    <Footer/>
      </div>
  )
}
