//Pages
import HomePage from "./homePage";
import Services from './services';
import Projects from './projects';
// Components
import Head from 'next/head';
import Navbar from '../components/Navbar';

export default function Spa() {
  return (
      <div className="font-semibold italic">
    <Head>
      <title>!NEXT </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/Brackets.png" />
    </Head>
    <Navbar/>
    <HomePage/>
    <br/>
    <Services/>
    <Projects/>

      </div>
  )
}
